{% set name = "atomsk" %}
{% set version = "0.13.1" %}
{% set sha256 = "8a4d40e16ee88268f3d498f854ec242b932f7f6b0f4b0c1a2b4e7b4e1b02b580" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pierrehirel/{{ name }}/archive/Beta-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - make.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - make
  host:
    - libblas
    - liblapack

test:
  commands:
    - atomsk --create fcc 4.02 Al aluminium.xsf

about:
  home: http://atomsk.univ-lille1.fr
  license: GPL-3.0
  license_family: GPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: The Swiss-army knife of atomic simulations

  description: |
    Atomsk is an Open Source command-line program dedicated to 
    the creation, manipulation, and conversion of atomic systems.
  doc_url: http://atomsk.univ-lille1.fr
  dev_url: https://github.com/pierrehirel/atomsk/

extra:
  recipe-maintainers:
    - jan-janssen
