{% set name = "atomsk" %}
{% set version = "0.10.4" %}
{% set sha256 = "ee5a6b2b14c49f9a6ef16244fe1c36e67bfee45d22442cf1dc666ad7bcaa31a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pierrehirel/{{ name }}/archive/Beta-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - make 
  host:
    - openblas
  run:
    - openblas

test:
  commands: 
    - atomsk --create fcc 4.02 Al aluminium.xsf

about:
  home: http://atomsk.univ-lille1.fr
  license: GPL-3.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'The Swiss-army knife of atomic simulations'

  description: |
    Atomsk is an Open Source command-line program dedicated to 
    the creation, manipulation, and conversion of atomic systems.
  doc_url: http://atomsk.univ-lille1.fr
  dev_url: https://github.com/pierrehirel/atomsk/

extra:
  recipe-maintainers:
    - jan-janssen
