appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: AVTZ5DR9Q5BbB5PdTlO2iehBP6gONaPRhjPblf2U4nzO1XFPfNk6BZ98H152iE/YpGrLTyA7mh1Kw0GR09Y2CpG052VFBi8KkZqFsHf22UOeGKItppOcIRpHiEJ+XB9z8h7pHtGZc8Mz6xx1HLvhqCiLMEL/jVYFENHj2VA9khOzGLbW6STBk0EVmez2yrPvzPKUcqxNpz1xqPgofIZjHvnvgGtov2BBGUSxQgcwNJQFElF+D3pOMj34aml01mF7JtmbA84grifESCMyfZhHx/3V0TlBjiHoJzGP2kgmgoFVJRu78YQ9FVcKWMBdjWR4rPTV+p9lc9eMjYTsb3fhDq6z95L1V0SqM25mR+MUEFIoVwwI/sL5wAtjSLB04okF3pdISqZQGQVWLqwnS0ajRY6WXuyMuCVisvfGk0310NGNHGjvzRd+NutlGzaLlDGFQ0BMfoLoXnKfFf79ODhKqbpKLx7p3E0kTb2Iy5hOuHLj+D0A9yRAhzIFUSvk6+I8kIPPdtrJRRPFvYy+BBFdNG+jyVN1l7m1JWo656phRrLeQJUy1jrpYY9j6fugUPx3W4LROBP1dGnaTdhzNvcas6ryFbjuyF0SeRg6r5z27hY4qQf2IQGfssLdYYS5X4K8Rwe0eWK8aQ2yAGQnWiWboubdB2uhQhNSF3TJNhHbNsY=}
conda_forge_output_validation: true
